#version 450 core

layout (local_size_x = 10, local_size_y = 10, local_size_z = 1) in;

layout (binding = 0, rgba8ui) uniform readonly uimage2D inputImage;
layout (binding = 2, rgba8ui) uniform writeonly uimage2D resultImage;

void main() {
	ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);

	vec3 rgb = imageLoad(inputImage, pixelCoords).rgb;

	ivec4 pixel = ivec4(rgb, 1.0);

    imageStore(resultImage, pixelCoords, pixel);
}